name: Build Docker for Android

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    
    
    - name: Build Docker
      run: |
        git clone https://github.com/tomxi1997/termux-packages termux-packages
        cd termux-packages
        sudo apt update && sudo apt install tk-dev -y 
        rm root-packages/containerd/too_long_path.patch
        sed -i 's/TERMUX_PKG_VERSION=1:/TERMUX_PKG_VERSION=/' ./root-packages/docker/build.sh
        sed -i 's/${TERMUX_PKG_VERSION:2}/${TERMUX_PKG_VERSION}/g' ./root-packages/docker/build.sh
        patch -p1 < $GITHUB_WORKSPACE/patches/docker.patch
        #cp $GITHUB_WORKSPACE/patches/cgroup.go.patch root-packages/docker/cgroup.go.patch
        #cp $GITHUB_WORKSPACE/patches/cgroups2.disable.patch root-packages/runc/cgroups2.disable.patch
        ./scripts/run-docker.sh ./build-package.sh -i --format debian docker docker-compose docker-buildx
        
        cd output
        mkdir data
        cp *.deb ./data/
        tar -czvf data.tar.xz data
        #bash $GITHUB_WORKSPACE/package_docker.sh
        #sudo chmod +x $GITHUB_WORKSPACE/*.sh
        #bash $GITHUB_WORKSPACE/repack.sh
        sudo cp data.tar.xz $GITHUB_WORKSPACE/
    
  
    - name: Upload package 
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: $GITHUB_WORKSPACE/data.tar.xz
